---
title: "ESM 206 Assignment 4 - Spiny Lobsters"
author: "Alex Ehrens & Courtney Krone"
date: "11/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(janitor)
library(tidyr)
library(here)
```

```{r}
lobster_abundance <- read.csv("lobster_abundance_sbc_lter.csv",
                              na = -99999) %>% 
  clean_names()
```

### 1. Introduction


### 2. Data and Methods


### 3. Results

#### a. Results A
IVEE and NAPL - MPA
AQUE, CARP and MOHK - Non-MPA
- Need to change color and show between MPA and NonMPA sites

```{r}
lobster_count <- lobster_abundance %>% 
  group_by(year, site) %>% 
  summarize(total_counts = sum(count))

ggplot(lobster_count, aes(x = year, y = total_counts)) +
  geom_col(aes(fill = site),show.legend = FALSE) +
  facet_wrap(~site)+
  labs(x = "Year (2012-2018)",
       y = "Total lobster counts",
       title = "Total lobster counts per site each year (2012-2018)",
       subtitle = "Source: SBC LTER",
       caption = "Lobster abundance increased between 2012 and 2018  for most of the sites excluding AQUE site./nThe MPA sites (IVEE and NAPL) lobster abundance grew substantially over the recorded years compared to non-MPA sites")
```

#### b. Results B

```{r}
lobster_size <- lobster_abundance %>% 
  filter(year %in% c("2012", "2018")) %>% 
  group_by(year, site) %>% 
  summarize(mean_size = mean(size_mm, na.rm = TRUE))


```

